import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";
import About from "../components/about/about";
import Education from "../components/education/education";
import Experience from "../components/experience/experience";
import Hero from "../components/hero/hero";

export default function Home() {
  return (
    <>
      <Head>
        <title>Mustafa ONAL</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <About />
      <Experience id="experience" />
      <Education id="education" />
    </>
  );
}
